# ObsidianDestroyer by Pandamoneous
# Now authored by drtshock and squidicuzz
# For information and updates visit http://dev.bukkit.org/server-mods/ObsidianDestroyer
# Made with love <3

# Do not touch this line. It will rewrite your config.
Version: ${project.version}

# This will only check for updates. We will never download them for you.
checkupdate: true

# The explosion radius that will affect blocks 
Radius: 3

# False means that water won't protect blocks from explosions.
FluidsProtect: true

# Whether or not you want to bypass fluid protect for all blocks.
BypassAllBlocks: false

# The id of the item you use to check durability.
CheckItemId: 38

# Setting this to true may cause errors with other plugins. But it will make us handle all explosions
# no matter what other plugins try to do.
IgnoreCancel: false

# Explosion types you want us to handle.
EnabledFor:
  TNT: true
  Cannons: false
  Creepers: false
  Ghasts: false
  Withers: false

# Durability = amount of explosions within the radius defined above
# within the time limit that will make a block blow up.
Durability:
  Enabled: true
  Obsidian: 3
  EnchantmentTable: 2
  EnderChest: 5
  Anvil: 2
  
 # Settings for bedrock. Recommended to be disabled or at a very high rate.
 # If enabled, people can blow holes in the bottom of your world.
  Bedrock:
    Enabled: false
    Durability: 100

# Reset will run a timer to clear the durability of blocks after a certain time.
# If you have issues with your server running out of memory then disabling this
# can save some memory :)
  ResetEnabled: true
  ResetAfter: '600000'
  
# Experimental Timer safety. Use this if you are having issues with your server running out of memory.
# This is not a fix to out of memory errors. Though it can help prevent this plugin from crashing your server.
# "SystemMinMemory" = Minimun amount (MegaBytes) of RAM that can be availabe.
# If there is less than this amount of memory available, no new timer threads will be created.
  UseTimerSafety: false
  SystemMinMemory: 80

# Chance to drop. Setting to anything at or above 1 will make them always drop.
Blocks:
  ChanceToDrop: 0.7
  
# Enables a bypass to allow explosions to effect blocks under/next to liquids.
Explosions:
  BypassAllFluidProtection: false
  TNTCannonsProtected: true
  
# Thats it :3