name: ObsidianDestroyer
main: com.drtshock.obsidiandestroyer.ObsidianDestroyer
version: ${project.version}
author: drtshock
softdepend: [Factions]

commands:
    obsidiandestroyer:
        description: ObisidanDestroyer
        usage: |
               /<command>
    od:
        description: ObisidanDestroyer
        usage: |
               /<command>